set(_CATKIN_CURRENT_PACKAGE "rosbag_info_pkg")
set(rosbag_info_pkg_VERSION "0.0.0")
set(rosbag_info_pkg_MAINTAINER "olga <olga@todo.todo>")
set(rosbag_info_pkg_PACKAGE_FORMAT "1")
set(rosbag_info_pkg_BUILD_DEPENDS "rosbag" "roscpp")
set(rosbag_info_pkg_BUILD_EXPORT_DEPENDS "rosbag" "roscpp")
set(rosbag_info_pkg_BUILDTOOL_DEPENDS "catkin")
set(rosbag_info_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(rosbag_info_pkg_EXEC_DEPENDS "rosbag" "roscpp")
set(rosbag_info_pkg_RUN_DEPENDS "rosbag" "roscpp")
set(rosbag_info_pkg_TEST_DEPENDS )
set(rosbag_info_pkg_DOC_DEPENDS )
set(rosbag_info_pkg_DEPRECATED "")