---
string id
byte passed
diagnostic_msgs/DiagnosticStatus[] status
  byte OK=0
  byte WARN=1
  byte ERROR=2
  byte STALE=3
  byte level
  string name
  string message
  string hardware_id
  diagnostic_msgs/KeyValue[] values
    string key
    string value
