#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import rosgraph
import rospy
from rostopic import ROSTopicHz


def get_parent_topics(topic, parent_topics=None, impl=False):
    global pubs, subs
    if parent_topics is None:
        parent_topics = []
    pub_nodes = [l for t, l in publications if t == topic]
    if not pub_nodes:
        return parent_topics
    for node in pub_nodes[0]:
        subs = [t for t, l in subscriptions if node in l]
        subs = filter(lambda x: x not in parent_topics, subs)  # get unique
        parent_topics.extend(subs)
        if not impl:
            return parent_topics
        for sub in subs:
            parent_topics = get_parent_topics(sub, parent_topics, impl=impl)
    return parent_topics


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('topics', nargs='+',
                        help='leaf topic names of topic graph')
    parser.add_argument('-p', '--search-parent', action='store_true',
                        help='search parent topics to check')
    args = parser.parse_args()
    topics = args.topics
    if args.search_parent:
        # get all parent topics
        parent_topics = []
        for topic in topics:
            parent_topics.extend(get_parent_topics(topic, impl=True))
        parent_topics = list(set(parent_topics))
        topics.extend(parent_topics)
    # prepare topic hz checkers
    rospy.loginfo('subscribing {} topics'.format(len(topics)))
    hz_checkers = []
    for t in topics:
        rt = ROSTopicHz(window_size=-1)
        hz_checkers.append(rt)
        rospy.Subscriber(t, rospy.AnyMsg, rt.callback_hz)
    rospy.loginfo('subscribed {} topics'.format(len(topics)))
    # main loop
    header = ['topic', 'rate', 'min_delta', 'max_delta', 'std_dev', 'window']
    while not rospy.is_shutdown():
        # collect topic hz stats
        stats = []
        max_col_width = [len(h) for h in header]
        for topic, rt in zip(topics, hz_checkers):
            hz_stat = rt.get_hz()
            if hz_stat is None:
                continue
            rate, min_delta, max_delta, std_dev, window = hz_stat
            stat = [topic, '{:.4}'.format(rate), '{:.4}'.format(min_delta),
                    '{:.4}'.format(max_delta), '{:.4}'.format(std_dev),
                    str(window)]
            stats.append(stat)
            for i, s in enumerate(stat):
                col_width = len(s)
                if col_width > max_col_width[i]:
                    max_col_width[i] = col_width
        if not stats:
            rospy.logwarn('no messages')
        else:
            stats = sorted(stats, key=lambda x: x[1], reverse=True)
            # compose table with left alignment
            for j, w in enumerate(max_col_width):
                header[j] = header[j].center(w)
                for i in range(len(stats)):
                    stats[i][j] = stats[i][j].ljust(w)
            # sum of col and each 3 spaces width
            table_width = sum(max_col_width) + 3 * (len(header) - 1)
            body = '\n'.join('   '.join(s for s in stat) for stat in stats)
            table = '''\
{header}
{hline}
{body}
'''.format(header='   '.join(header), hline='=' * table_width, body=body)
            print(table)
        # wait for next check
        rospy.rostime.wallsleep(1.0)


if __name__ == '__main__':
    NAME = 'topic_hz_monitor'
    ID = '/' + NAME
    rospy.init_node(NAME, anonymous=True)
    master = rosgraph.Master(ID)
    state = master.getSystemState()
    publications, subscriptions, _ = state
    main()
